### ISSUE TITLE
Translate documentation into German

### ISSUE THREAD

**Issue by a1300** [AntShares/docs#9]
I would like to translate the current state of the documentation into German. I unfortunately only understand English and German. Is it ok to translate the docs from English to German?

**Comment by canesin** [comment]
Hey, yes it is - In the process feel free to improve the English docs .. are you in the github org ? We are still bootstraping it and I can add you and as a collaborator on this very own repository

**Comment by erikzhang** [comment]
@a1300 It's OK.

**Comment by a1300** [comment]
Ok :-) I'm still working on it. I try to push the translations this weekend.

**Comment by erikzhang** [comment]
Great!
